Repository cyberVirtua/dxp, pull requests merged in 2021-07, with the labels that each got.

#25 Handle errors
  CMakeLists.txt
  src/CMakeLists.txt
  src/daemon.cpp
  src/daemon.hpp
  src/desktop.cpp
  src/dexpo-daemon.cpp
  src/dexpo.cpp
  src/drawable.cpp
  src/drawable.hpp
  src/socket.cpp
  src/socket.hpp
  src/window.cpp
  src/window.hpp
  src/xcb_util.cpp
  src/xcb_util.hpp
Labels: enhancement

#43 Undo big-screen fix as everything works fine without it
  src/desktop.cpp
  src/desktop.hpp
Labels: enhancement

#45 Remove aliasing on resized screenshots
  .clang-tidy
  src/desktop.cpp
  src/desktop.hpp
Labels: enhancement, gui

#46 Rename dexpo to dxp
  CMakeLists.txt
  README.md
  src/CMakeLists.txt
  src/config.hpp
  src/daemon.cpp
  src/desktop.cpp
  src/dxp.cpp
  src/dxpd.cpp
  src/socket.cpp
  src/socket.hpp
  src/window.cpp
  src/window.hpp
  src/xcb_util.cpp
Labels: enhancement

#49 Extend configurability of dxp's position on screen
  src/config.hpp
  src/drawable.cpp
  src/drawable.hpp
  src/dxp.cpp
  src/window.cpp
  src/window.hpp
  src/xcb_util.cpp
  src/xcb_util.hpp
Labels: enhancement

#52 Cache the most recent desktop returned by `get_hover_desktop`
  src/desktop.cpp
  src/drawable.cpp
  src/drawable.hpp
  src/dxp.cpp
  src/window.cpp
  src/window.hpp
Labels: enhancement

#53 Run Include-what-you-use on the project and apply fixes
  src/daemon.cpp
  src/daemon.hpp
  src/desktop.cpp
  src/desktop.hpp
  src/drawable.hpp
  src/dxp.cpp
  src/dxpd.cpp
  src/socket.cpp
  src/socket.hpp
  src/window.cpp
  src/window.hpp
  src/xcb_util.cpp
  src/xcb_util.hpp
Labels: enhancement

#50 Configre keybinds with keynames
  src/CMakeLists.txt
  src/config.hpp
  src/daemon.cpp
  src/daemon.hpp
  src/desktop.cpp
  src/desktop.hpp
  src/drawable.cpp
  src/drawable.hpp
  src/dxp.cpp
  src/dxpd.cpp
  src/keys.hpp
  src/socket.cpp
  src/socket.hpp
  src/window.cpp
  src/window.hpp
  src/xcb_util.cpp
  src/xcb_util.hpp
Labels: gui
