Repository cyberVirtua/dxp, pull requests merged in 2021-06, with the labels that each got.

#4 Add a class to manage desktop screenshots
  .clang-tidy
  CMakeLists.txt
  cmake/CompilerWarnings.cmake
  src/CMakeLists.txt
  src/desktop_pixmap.cpp
  src/desktop_pixmap.hpp
  src/dexpo.cpp
  src/drawable.cpp
  src/drawable.hpp
  src/drawtypes/DesktopPreview.hpp
  src/drawtypes/Window.hpp
  src/example_desktop_pixmap_usage.cpp
Labels: backend

#7 Display screenshots and a border around preselected
  src/CMakeLists.txt
  src/config.hpp
  src/desktop_pixmap.cpp
  src/dexpo.cpp
  src/example_desktop_pixmap_usage.cpp
  src/window.cpp
  src/window.hpp
Labels: gui

#8 Daemon that will screenshot desktops and expose them through sockets
  src/CMakeLists.txt
  src/daemon.cpp
  src/desktop_pixmap.cpp
  src/desktop_pixmap.hpp
  src/drawable.cpp
  src/drawable.hpp
Labels: backend

#10 Handle keyboard and mouse events: move desktop preselection, close application and more
  src/CMakeLists.txt
  src/desktop_pixmap.cpp
  src/dexpo.cpp
  src/window.cpp
  src/window.hpp
  src/wmctrl.cpp
  src/wmctrl.hpp
Labels: gui

#11 Send downsized RGBA pixmaps over sockets
  .clang-tidy
  .gitignore
  src/CMakeLists.txt
  src/config.hpp
  src/daemon.cpp
  src/desktop_pixmap.cpp
  src/desktop_pixmap.hpp
  src/dexpo.cpp
  src/dexpo_socket.cpp
  src/dexpo_socket.hpp
  src/window.cpp
  src/wmctrl.cpp
Labels: backend

#20 Code style and quality
  .clang-tidy
  src/CMakeLists.txt
  src/config.hpp
  src/daemon.cpp
  src/desktop.cpp
  src/desktop.hpp
  src/dexpo.cpp
  src/drawable.cpp
  src/socket.cpp
  src/socket.hpp
  src/window.cpp
  src/window.hpp
  src/wmctrl.cpp
  src/wmctrl.hpp
  src/xcb_util.cpp
  src/xcb_util.hpp
Labels: enhancement

#23 Link common files as an Object Library. Closes #19
  CMakeLists.txt
  cmake/StandardProjectSettings.cmake
  src/CMakeLists.txt
Labels: enhancement

#26 UX improved & fixes added
  .clang-tidy
  src/config.hpp
  src/daemon.cpp
  src/desktop.cpp
  src/desktop.hpp
  src/dexpo.cpp
  src/drawable.cpp
  src/drawable.hpp
  src/socket.cpp
  src/window.cpp
  src/window.hpp
  src/xcb_util.cpp
  src/xcb_util.hpp
Labels: gui
